// SocialZen keyword lists.
// Edit these arrays directly. Keep one phrase per line for easy maintenance.

var BLOCK_KEYWORDS = [
  // Easy smoke-test terms. These are intentionally broad for the first demo.
  "socialzen test",
  "check",
  "cool",
  "heart",
  "love",
  "look",
  "at",
  "mad",
  "news",
  "navy",

  // People and movements
  "donald trump",
  "trump",
  "tucker carlson",
  "ben shapiro",
  "trump administration",
  "trump news",
  "trump meltdown",
  "trump derangement",
  "president trump",
  "maga",
  "make america great again",
  "biden",
  "joe biden",
  "biden administration",
  "biden news",
  "hunter biden",
  "harris",
  "kamala harris",
  "republican",
  "republicans",
  "gop",
  "democrat",
  "democrats",
  "democratic party",
  "liberal",
  "conservative",
  "progressive",
  "far left",
  "far right",
  "qanon",
  "truth social",
  "truthsocial",
  "truth social post",

  // Elections and government
  "election",
  "elections",
  "vote",
  "voting",
  "voter",
  "ballot",
  "polling place",
  "campaign",
  "campaigning",
  "midterm",
  "midterms",
  "primary election",
  "presidential election",
  "congress",
  "congressional",
  "senate",
  "senator",
  "house of representatives",
  "representative",
  "governor",
  "governor race",
  "supreme court",
  "white house",
  "whitehouse.gov",
  "oval office",
  "capitol",
  "legislation",
  "bill passed",
  "impeachment",
  "politics",
  "political",
  "politician",
  "government shutdown",
  "executive order",

  // Common political conflict and outrage language
  "political chaos",
  "political meltdown",
  "breaking politics",
  "culture war",
  "woke",
  "cancel culture",
  "fake news",
  "stolen election",
  "election fraud",
  "deep state",
  "liberal tears",
  "own the libs",
  "triggered liberal",
  "maga meltdown",
  "political outrage",
  "political scandal",
  "traitor",
  "treason",
  "fascist",
  "communist",

  // Gender-war and emotion-spurring conflict phrases
  "men are awful",
  "women are awful",
  "all men",
  "all women",
  "men vs women",
  "men versus women",
  "men are trash",
  "women are trash",
  "male privilege",
  "female privilege",
  "misogynist",
  "misandrist",
  "gender war",
  "battle of the sexes"
];

// Add phrases here to force a post to remain visible.
// Override matches always win over block matches.
var OVERRIDE_KEYWORDS = [];
